In [105]:
import pandas as pd
import os

In [3]:
# expression matrix
exp_path = 'TcellDev/Data/T_cell_development/integrated/t_data.txt'

# cluster ids and cell type ids
id_path = 'TcellDev/Data/T_cell_development/integrated/cluster_pseudotime.txt'

In [4]:
exp = pd.read_csv(exp_path, sep = "\t")

In [25]:
exp = exp.rename(columns = {'Unnamed: 0':'gene_id'})

In [27]:
exp.head()

,gene_id,TACGGTATCAGTTAGC_1,CGTTCTGGTAGAAAGG_1,TGAGAGGGTACGAAAT_1,GCTCCTATCAGAAATG_2,GCGCGATCAGCCTTTC_2,CTAATGGGTGTTTGTG_1,GTCACAAAGATCGATA_1,GTATTCTGTTGTTTGG_1,AGTCTTTTCACCTTAT_2,...,ATTGGACGTCATATCG_2,ACGGGTCAGCTAGTCT_1,AACTCTTGTATGAATG_1,CCCAATCCATTAACCG_1,CCAGCGACATCTATGG_1,CCCAGTTCACAAGTAA_1,TTGGAACCATGCGCAC_1,CTGTGCTAGCTTCGCG_2,TGCGCAGGTGCGCTTG_2,GTGGGTCCAGCCTTTC_1
0,Mrpl15,0.850588,1.068103,0.00000,0.888734,1.324457,0.000000,0.9919,0.915991,0.000000,...,0.000000,0.0,0.0,0.901838,1.096749,0.0,0.645935,0.000000,0.000000,0.00000
1,Lypla1,0.850588,0.000000,0.00000,0.000000,0.000000,0.000000,0.9919,0.000000,1.095158,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,1.358346,0.90859
2,Tcea1,0.850588,0.000000,0.00000,0.000000,0.000000,0.000000,0.9919,0.915991,1.095158,...,0.799977,0.0,0.0,0.901838,0.000000,0.0,0.645935,0.712599,0.000000,0.90859
3,Atp6v1h,0.000000,0.000000,0.00000,0.000000,0.000000,1.450139,0.0000,0.000000,1.095158,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,1.358346,0.00000
4,Rb1cc1,0.850588,1.068103,0.78639,0.000000,0.652350,0.000000,0.0000,0.000000,1.605291,...,0.000000,0.0,0.0,0.000000,1.096749,0.0,1.035154,0.000000,0.893995,0.00000

In [28]:
exp.shape

(14414, 3186)

In [35]:
id_info = pd.read_csv(id_path, sep = "\t")
id_info = id_info.rename(columns = {'Unnamed: 0':'barcode'})

In [36]:
id_info

,barcode,orig.ident,nCount_RNA,nFeature_RNA,percent.mt,stim,seurat_clusters,RNA_snn_res.1,stage,bigstage,color,PBA_order
0,TACGGTATCAGTTAGC_1,Self,7457,2156,3.728041,Self,12,12,DN,DN,darkcyan,0.211898
1,CGTTCTGGTAGAAAGG_1,Self,5236,1991,3.781513,Self,12,12,DN,DN,darkcyan,0.239283
2,TGAGAGGGTACGAAAT_1,Self,8365,2529,3.371189,Self,12,12,DN,DN,darkcyan,0.218463
3,GCTCCTATCAGAAATG_2,Tabula,6983,2507,2.420163,Tabula,12,12,DN,DN,darkcyan,0.227197
4,GCGCGATCAGCCTTTC_2,Tabula,10869,3112,2.474929,Tabula,12,12,DN,DN,darkcyan,0.251930
...,...,...,...,...,...,...,...,...,...,...,...,...
3180,CCCAGTTCACAAGTAA_1,Self,4297,1539,2.885734,Self,8,8,CD8,CD8,#BB4A94,1.535600
3181,TTGGAACCATGCGCAC_1,Self,11016,2793,2.995643,Self,8,8,CD8,CD8,#BB4A94,1.301503
3182,CTGTGCTAGCTTCGCG_2,Tabula,9622,2334,2.525462,Tabula,8,8,CD8,CD8,#BB4A94,1.524193
3183,TGCGCAGGTGCGCTTG_2,Tabula,6921,2322,2.225112,Tabula,8,8,CD8,CD8,#BB4A94,1.501979
3184,GTGGGTCCAGCCTTTC_1,Self,6753,1770,2.532208,Self,8,8,CD8,CD8,#BB4A94,1.524600

In [69]:
# transpose 
exp_alt = exp.transpose()

In [70]:
exp_alt.columns = exp_alt.loc['gene_id']

exp_alt = exp_alt.drop(labels = 'gene_id', axis = 0)

In [76]:
exp_alt['barcode'] = exp_alt.index

In [78]:
exp_alt = exp_alt.reset_index(drop = True)

In [81]:
exp_alt

gene_id,Mrpl15,Lypla1,Tcea1,Atp6v1h,Rb1cc1,4732440D04Rik,Pcmtd1,Gm26901,Rrs1,Mybl1,...,Rbp4,Plce1,Gm16244,Gpam,Gm9529,Gm7102,AC133103.1,AC132444.1,AC125149.2,barcode
0,0.850588,0.850588,0.850588,0.0,0.850588,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TACGGTATCAGTTAGC_1
1,1.068103,0.0,0.0,0.0,1.068103,0.0,1.068103,0.0,1.068103,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CGTTCTGGTAGAAAGG_1
2,0.0,0.0,0.0,0.0,0.78639,0.0,1.523089,0.0,0.78639,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TGAGAGGGTACGAAAT_1
3,0.888734,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.351728,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,GCTCCTATCAGAAATG_2
4,1.324457,0.0,0.0,0.0,0.65235,0.65235,1.043838,0.0,1.043838,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,GCGCGATCAGCCTTTC_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3180,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CCCAGTTCACAAGTAA_1
3181,0.645935,0.0,0.645935,0.0,1.035154,0.645935,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TTGGAACCATGCGCAC_1
3182,0.0,0.0,0.712599,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CTGTGCTAGCTTCGCG_2
3183,0.0,1.358346,0.0,1.358346,0.893995,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TGCGCAGGTGCGCTTG_2
3184,0.0,0.90859,0.90859,0.0,0.0,0.0,0.0,0.0,1.37666,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,GTGGGTCCAGCCTTTC_1

In [82]:
# left join to get IDs for barcodes
exp_df_join = exp_alt.merge(id_info[['barcode', 'bigstage']], left_on = 'barcode',
                          right_on = 'barcode')

In [87]:
exp_df_join

,Mrpl15,Lypla1,Tcea1,Atp6v1h,Rb1cc1,4732440D04Rik,Pcmtd1,Gm26901,Rrs1,Mybl1,...,Plce1,Gm16244,Gpam,Gm9529,Gm7102,AC133103.1,AC132444.1,AC125149.2,barcode,bigstage
0,0.850588,0.850588,0.850588,0.0,0.850588,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TACGGTATCAGTTAGC_1,1DN
1,1.068103,0.0,0.0,0.0,1.068103,0.0,1.068103,0.0,1.068103,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CGTTCTGGTAGAAAGG_1,1DN
2,0.0,0.0,0.0,0.0,0.78639,0.0,1.523089,0.0,0.78639,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TGAGAGGGTACGAAAT_1,1DN
3,0.888734,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.351728,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,GCTCCTATCAGAAATG_2,1DN
4,1.324457,0.0,0.0,0.0,0.65235,0.65235,1.043838,0.0,1.043838,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,GCGCGATCAGCCTTTC_2,1DN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3180,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CCCAGTTCACAAGTAA_1,7CD8sp
3181,0.645935,0.0,0.645935,0.0,1.035154,0.645935,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TTGGAACCATGCGCAC_1,7CD8sp
3182,0.0,0.0,0.712599,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CTGTGCTAGCTTCGCG_2,7CD8sp
3183,0.0,1.358346,0.0,1.358346,0.893995,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TGCGCAGGTGCGCTTG_2,7CD8sp
3184,0.0,0.90859,0.90859,0.0,0.0,0.0,0.0,0.0,1.37666,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,GTGGGTCCAGCCTTTC_1,7CD8sp

In [84]:
# rename these to match
exp_df_join['bigstage'] = exp_df_join['bigstage'].replace({'DN': '1DN', 'ISP': '2preDP', 'DPbla':'3DPbla',
                                        'DPre': '4DPre', 'DPsel': '5DPsel', 'CD4': '6CD4sp',
                                        'CD8': '7CD8sp'})


# array(['6CD4sp', '10APC', '5DPsel', '4DPre', '2preDP', '3DPbla', '1DN',
#        '7CD8sp', '9NCL']

In [89]:
# add time column
exp_df_join['time'] = exp_df_join['bigstage'].replace({'1DN':1, '2preDP':2, '3DPbla':3, '4DPre':4,
                                          '5DPsel':5, '6CD4sp':6, '7CD8sp':6})

In [90]:
exp_df_join

,Mrpl15,Lypla1,Tcea1,Atp6v1h,Rb1cc1,4732440D04Rik,Pcmtd1,Gm26901,Rrs1,Mybl1,...,Gm16244,Gpam,Gm9529,Gm7102,AC133103.1,AC132444.1,AC125149.2,barcode,bigstage,time
0,0.850588,0.850588,0.850588,0.0,0.850588,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TACGGTATCAGTTAGC_1,1DN,1
1,1.068103,0.0,0.0,0.0,1.068103,0.0,1.068103,0.0,1.068103,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CGTTCTGGTAGAAAGG_1,1DN,1
2,0.0,0.0,0.0,0.0,0.78639,0.0,1.523089,0.0,0.78639,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TGAGAGGGTACGAAAT_1,1DN,1
3,0.888734,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.351728,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,GCTCCTATCAGAAATG_2,1DN,1
4,1.324457,0.0,0.0,0.0,0.65235,0.65235,1.043838,0.0,1.043838,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,GCGCGATCAGCCTTTC_2,1DN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3180,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CCCAGTTCACAAGTAA_1,7CD8sp,6
3181,0.645935,0.0,0.645935,0.0,1.035154,0.645935,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TTGGAACCATGCGCAC_1,7CD8sp,6
3182,0.0,0.0,0.712599,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CTGTGCTAGCTTCGCG_2,7CD8sp,6
3183,0.0,1.358346,0.0,1.358346,0.893995,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TGCGCAGGTGCGCTTG_2,7CD8sp,6
3184,0.0,0.90859,0.90859,0.0,0.0,0.0,0.0,0.0,1.37666,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,GTGGGTCCAGCCTTTC_1,7CD8sp,6

In [91]:
dfcols = exp_df_join.columns.tolist()
reorder_cols = dfcols[-3:] + dfcols[:-3]

In [92]:
exp_df2 = exp_df_join[reorder_cols]

In [99]:
# put time before bistage
dfcols = exp_df2.columns.tolist()
reorder_cols = [dfcols[0], dfcols[2], dfcols[1]] +  dfcols[3:]

In [100]:
exp_df2 = exp_df2[reorder_cols]

In [102]:
# drop cols with all zeros
exp_df3 = exp_df2.loc[:, (exp_df2 != 0).any(axis = 0)]

In [103]:
exp_df3

,barcode,time,bigstage,Mrpl15,Lypla1,Tcea1,Atp6v1h,Rb1cc1,4732440D04Rik,Pcmtd1,...,Ifit1bl2,Rbp4,Plce1,Gm16244,Gpam,Gm9529,Gm7102,AC133103.1,AC132444.1,AC125149.2
0,TACGGTATCAGTTAGC_1,1,1DN,0.850588,0.850588,0.850588,0.0,0.850588,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,CGTTCTGGTAGAAAGG_1,1,1DN,1.068103,0.0,0.0,0.0,1.068103,0.0,1.068103,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,TGAGAGGGTACGAAAT_1,1,1DN,0.0,0.0,0.0,0.0,0.78639,0.0,1.523089,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,GCTCCTATCAGAAATG_2,1,1DN,0.888734,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,GCGCGATCAGCCTTTC_2,1,1DN,1.324457,0.0,0.0,0.0,0.65235,0.65235,1.043838,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3180,CCCAGTTCACAAGTAA_1,6,7CD8sp,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3181,TTGGAACCATGCGCAC_1,6,7CD8sp,0.645935,0.0,0.645935,0.0,1.035154,0.645935,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3182,CTGTGCTAGCTTCGCG_2,6,7CD8sp,0.0,0.0,0.712599,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3183,TGCGCAGGTGCGCTTG_2,6,7CD8sp,0.0,1.358346,0.0,1.358346,0.893995,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3184,GTGGGTCCAGCCTTTC_1,6,7CD8sp,0.0,0.90859,0.90859,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [104]:
# save
exp_df3.to_csv('integrated_data.E', sep = "\t", index = False)

# example from repo

In [149]:
# from the example repo
exdf = pd.read_csv('/net/dali/home/mscbio/aar126/genomics/scdiff2/example/example.E', sep = "\t")

In [150]:
exdf

,cell_name,time_point,assignment,0610007C21Rik,0610007L01Rik,0610007N19Rik,0610007P08Rik,0610007P14Rik,0610007P22Rik,0610009B22Rik,...,Zwint,Zxda,Zxdb,Zxdc,Zyg11b,Zyx,Zzef1,Zzz3,l7Rn6,rtTA
0,1_iN2_C02,0,MEF,6.341676,0.000000,0.000000,0.000000,5.690383,0.000000,2.556539,...,4.829228,0.0,0.000000,0.000000,2.895336,1.682171,1.139292,0.000000,2.065228,0.000000
1,1_iN2_C05,0,MEF,4.959945,6.231432,0.000000,0.000000,6.055019,4.024706,4.957429,...,5.320143,0.0,0.000000,0.010157,1.912734,5.838476,0.000000,3.642170,5.092430,0.000000
2,1_iN2_C07,0,MEF,0.000000,0.000000,3.888991,0.041368,5.530216,1.793932,0.000000,...,5.096867,0.0,0.000000,0.000000,0.000000,2.614466,2.145846,3.864990,1.989720,0.000000
3,1_iN2_C08,0,MEF,4.697531,3.062912,0.000000,0.000000,0.693764,4.297325,4.853152,...,6.068946,0.0,0.000000,0.000000,0.000000,7.464196,3.407588,0.000000,3.995451,0.000000
4,1_iN2_C09,0,MEF,6.609152,6.627976,5.559868,3.247370,6.673742,0.000000,5.390071,...,6.639057,0.0,0.000000,0.000000,0.000000,7.933592,1.933924,0.000000,3.627951,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,1ggS_iN4_C67,22,Neuron,2.415375,6.725156,0.000000,0.000000,0.000000,2.295439,0.000000,...,4.324884,0.0,0.000000,0.000000,5.542317,0.539820,0.000000,0.000000,0.000000,5.958162
248,1gL_iN4_C02,22,Fibroblast,6.489037,4.404424,4.184277,2.311201,4.459130,3.554364,6.509553,...,3.597637,0.0,2.402421,0.924023,0.571557,4.965917,0.019243,0.975106,4.752770,0.000000
249,1gL_iN4_C31,22,Fibroblast,7.409229,5.107711,4.009006,0.000000,3.430740,2.524009,1.500461,...,5.825282,0.0,0.000000,2.183213,1.254021,7.190141,0.000000,0.000000,5.681482,0.000000
250,1gL_iN4_C39,22,Myocyte,4.128706,0.000000,0.000000,0.000000,4.580872,0.000000,6.351578,...,0.000000,0.0,0.000000,0.000000,1.862890,6.099715,0.000000,1.623088,0.000000,5.621044
251,1gM_iN4_C42,22,Fibroblast,6.616127,0.000000,4.209771,5.131456,7.495259,1.837260,5.385572,...,1.604785,0.0,0.000000,3.468716,0.000000,6.061304,3.275710,4.260047,4.541520,0.000000